version: '3'
volumes:
  mongo_data: null
networks:
  cockpit_network:
    driver: bridge     
services:
  cms:
    build: 
      context: ./
      dockerfile: ./Dockerfile
    environment:
      COCKPIT_SESSION_NAME: cockpit
      COCKPIT_SALT: _create_your_own_
      COCKPIT_DATABASE_SERVER: 'mongodb://mongo:27017'
      COCKPIT_DATABASE_NAME: cockpit_master
      COCKPIT_DATABASE_USERNAME: root
      COCKPIT_DATABASE_PASSWORD: example
    depends_on:
      - mongo
    ports:
      - "8089:80"
    networks:
      - cockpit_network
    volumes: 
      - ./:/var/www/html  

  mongo:
   container_name: cpit_db
   image: mongo:latest
   restart: always     
   volumes:
      - mongo_data:/data/db
   networks:
     - cockpit_network
   environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
     - 8088:8081
    networks:
     - cockpit_network
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example     
