version: '3'
volumes:
  mongo_data: null
networks:
  cockpit_network:
    driver: bridge     
services:
  cms:
    image: agentejo/cockpit
    environment:
      COCKPIT_SESSION_NAME: cockpit
      COCKPIT_SALT: _create_your_own_
      COCKPIT_DATABASE_SERVER: 'mongodb://db:27017'
      COCKPIT_DATABASE_NAME: cockpit_master
    depends_on:
      - db
    ports:
      - "8089:80"
    networks:
      - cockpit_network

  db:
   container_name: cpit_db
   image: mongo:latest     
   volumes:
      - mongo_data:/data/db
   networks:
     - cockpit_network      

